# Generated by Django 4.0.1 on 2022-02-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_friend_accepted_at_remove_friend_is_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='contact number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], max_length=1, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'single'), ('married', 'married'), ('widowed', 'widowed'), ('divorced', 'divorced'), ('separated', 'separated')], max_length=15, null=True, verbose_name='marital status'),
        ),
    ]
