# Generated by Django 4.0.1 on 2022-02-08 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_city_alter_user_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('inviter', 'invitee')},
        ),
    ]
