# Generated by Django 4.0.1 on 2022-01-26 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeelingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('F', 'feeling'), ('A', 'activity')], max_length=1, verbose_name='type')),
                ('name', models.CharField(max_length=15, verbose_name='name')),
                ('status_description', models.CharField(max_length=50, verbose_name='status description')),
            ],
            options={
                'verbose_name': 'feeling/activity',
                'verbose_name_plural': 'feeling/activity',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('checkin', models.CharField(blank=True, max_length=100, null=True, verbose_name='checkin')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('feeling_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.feelingactivity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_of_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostTagFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_friend_of_post', to='post.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_is_tagged', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='post/media/', verbose_name='media')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_of_post', to='post.post')),
            ],
        ),
    ]
