# Generated by Django 4.0.1 on 2022-02-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='type',
            field=models.CharField(choices=[('I', 'individual'), ('G', 'group')], default='I', max_length=1),
        ),
    ]
